name: Java Test & Release

on:
  push:
    tags:
      - 'v*.*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java_version: [ 16, 17, 18 ]
        # java_dist: [ adopt-hotspot, adopt-openj9, temurin, zulu, corretto ]
        java_dist: [ adopt-openj9 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.java_dist }}
          java-version: ${{ matrix.java_version }}
          cache: 'gradle'
      - if: ${{ matrix.os != 'windows-latest' }}
        run: chmod +x ./gradlew
      - run: ./gradlew test --no-daemon

  release:
    needs: [ test ] # wait for testing to finish
    if: ${{ success() }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt-openj9
          java-version: 17
          cache: 'gradle'
      - run: chmod +x ./gradlew
      - run: ./gradlew copyJars publish
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            ${{ github.workspace }}/jars/*.jar
            ${{ github.workspace }}/LICENSE
